### ISSUE TITLE
Audio not work

### ISSUE THREAD

**Issue by Artroeb** [CharlesCCC/Asus-Prime-Z490-A-OpenCore-Hackintosh#1]
Remove fakepciid and fakepciid-intel-hdmi but audion not work

**Comment by CharlesCCC** [comment]
have you tried set the alcid ? what's your setting ? you might compare it with my config.

**Comment by CharlesCCC** [comment]
Make sure get the PCI device added to config 

as 

https://github.com/CharlesCCC/Asus-Prime-Z490-A-OpenCore-Hackintosh/commit/88145f940b2a345e2d75b9f9cd4bf41ffd35771b#diff-18ce8f2001c3c18075dbf54219a44cbfbc93fc79f0f2ab519305ed1bcd16112eL275
